Beyond-Imagination/DocuLink

manifest.yml
src/index.js
static/hello-world/src/App.js
static/hello-world/src/components/search.js

1. Search Component
2. Link page Event

Search component

---

static/hello-world/src/App.js
static/hello-world/src/components/SearchBar.jsx
static/hello-world/src/components/SwitchButton.jsx

1. search bar refactoring from js to jsx
2. responsive width
3. 2d version available to search
4. re location toggle btn(3d<->2d)

feat: search-bar refactoring and responsive width

---

src/index.js
static/hello-world/src/App.js

1. using cql
2. add searching state

feat: search component

---

static/hello-world/src/App.js
static/hello-world/src/components/Checkbox.jsx

feat: checkbox component

---

manifest.yml
src/index.js
static/hello-world/src/App.js

- node hover event
I add new scope `read:confluence-user` because I added to user info of each page.

feat: node hover event

---

manifest.yml
src/index.js
static/hello-world/src/App.js
static/hello-world/src/components/Checkbox.jsx

page hierarchy 로 node 연결을 추가합니다

feat: page hierarchy

---

manifest.yml
src/index.js
static/hello-world/src/App.js

feat: seperate nodes and links

---

manifest.yml

route 를 기본값에서 doculink 로 변경합니다

chore: change route

---

static/hello-world/src/App.js
static/hello-world/src/components/Checkbox.jsx

feat: checkbox tooltip DOCULINK-31

---

src/index.js
static/hello-world/src/App.js

keyword 와 hierarchy 의 link 색을 구분합니다

feat: different link color

---

static/hello-world/src/App.js
static/hello-world/src/components/Checkbox.jsx
static/hello-world/src/utils/utils.js

DOCULINK-37 - Node color

---

manifest.yml
src/be/index.js
src/fe/src/App.js
src/fe/src/utils/utils.js
src/index.js

feat: labels

---

src/fe/src/App.js
src/fe/src/components/PageNodeTooltip.jsx

UI - Update
1. page node tooltip content enhancement
2. Fix what page hover doesn't work in the search box

Doculink 40

---

src/be/api.js
src/fe/src/App.js

API의 응답 타입을 수정하였습니다.
- getKeywordGraphs, getHierarchy의 응답을 link array로 수정
- getNodes의 응답을 node array로 수정
- FE에서 바뀐 응답에 맞춰 state 설정 변경

refactor: change the response type of API

---

src/fe/src/App.js

#27 과정으로 인한 fe의 type 오류를 해결합니다.

fix: resolve type error by adjusting nodes structure

---

src/fe/src/App.js
src/fe/src/components/Checkbox.jsx
src/fe/src/components/SyncConfirmModal.jsx

- fix sync btn bug
- add confirm btn before sync

Doculink 59

---

src/fe/package-lock.json
src/fe/package.json
src/fe/src/App.js

노드를 title에서 원으로 변경합니다. 2D의 경우 확대하는 경우 node title이 하단에 나올 수 있도록 하였습니다.

feat: change node shape from title to circle

---

src/fe/src/App.js

gemini review에 따라 for 문을 forEach으로 변경합니다. 
gemini 코드를 그대로 사용하면 새로운 node 객체가 생성되어 forceGraph에 문제가 생기기 때문에 forEach을 이용해 node 객체가 새롭게 생성되지 않도록 약간의 수정을 추가합니다.

refactor: replace for loop with forEach for handleSearch

---

src/be/api.js

각 background job 별 작업중인 document 개수를 로그로 남깁니다

feat: log document count

---

src/fe/src/components/ColorPicker.jsx

+ color picker에서 alpha 값 변경이 정상적으로 동작하지 않는 문제를 해결합니다.
+ color picker의 값 변경이 customInput에 반영되지 않는 문제를 해결합니다.

fix: synchronize color picker input fields with brightness controls

---

src/fe/src/App.js
src/fe/src/components/Modal.jsx

rovo link 관련한 버그들을 해결합니다.
+ rovo의 초기값이 빈 배열이기 때문에 rovo 데이터가 없는 경우에도 modal창이 나오지 않는 문제를 해결합니다.
+ rovo modal이 라이트모드, 다크모드 지원을 하고 있지 않아 지원을 하도록 수정합니다.

fix: correct rovo button behavior
